// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuekhoyygnbxhcxlyksj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1ZWtob3l5Z25ieGhjeGx5a3NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MjI5NzksImV4cCI6MjA1Nzk5ODk3OX0.Vga09HwIcqDqBvVElBtaHodJcu_PiMO028rQhJkcXNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);